# Generated by Django 4.2.29 on 2026-03-24 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("volunteer", "Volunteering"),
                            ("donation", "Donation"),
                            ("partnership", "Partnership"),
                            ("media", "Media/Press"),
                            ("complaint", "Complaint"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "reply",
                    models.TextField(
                        blank=True, help_text="Staff reply to this message"
                    ),
                ),
                ("replied_by", models.CharField(blank=True, max_length=100)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_replied", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("donor_email", models.EmailField(max_length=254)),
                (
                    "donor_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[\\d\\s-]{10,}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("stationery", "Stationery & Books"),
                            ("uniforms", "School Uniforms"),
                            ("shoes", "Shoes"),
                            ("sanitary", "Sanitary Pads"),
                            ("undergarments", "Undergarments"),
                            ("hygiene", "Hygiene Products"),
                            ("other", "Other Items"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "item_description",
                    models.TextField(help_text="Quantity, condition, etc."),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Approximate quantity", null=True
                    ),
                ),
                ("drop_off_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("received", "Received"),
                            ("distributed", "Distributed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this donation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Donation Offer",
                "verbose_name_plural": "Donation Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "name",
                    models.CharField(blank=True, help_text="Optional", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("description", models.TextField(blank=True)),
                ("is_upcoming", models.BooleanField(default=True)),
                ("volunteers_needed", models.PositiveIntegerField(default=0)),
                ("volunteers_confirmed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Outreach Event",
                "verbose_name_plural": "Outreach Events",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if individual",
                        max_length=200,
                    ),
                ),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[\\d\\s-]{10,}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Sponsor"),
                            ("corporate", "Corporate/Organization"),
                            ("school", "School/Institution"),
                            ("ngo", "NGO/Non-profit"),
                            ("government", "Government Agency"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "proposal",
                    models.TextField(
                        help_text="Describe partnership proposal or interest"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Inquiry"),
                            ("reviewing", "Under Review"),
                            ("meeting", "Meeting Scheduled"),
                            ("negotiating", "Negotiating"),
                            ("partnered", "Partnered"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this partnership"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partnership Inquiry",
                "verbose_name_plural": "Partnership Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[\\d\\s-]{10,}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "volunteer_type",
                    models.CharField(
                        choices=[
                            ("event", "Event Volunteer (May 8th)"),
                            ("preparation", "Preparation/Sorting"),
                            ("remote", "Remote Support"),
                            ("regular", "Regular Volunteer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Skills, availability, or special requests",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("attended", "Attended"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this volunteer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_contacted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Volunteer Application",
                "verbose_name_plural": "Volunteer Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="core.outreachevent",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_attended",
                        to="core.volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Attendance",
                "verbose_name_plural": "Event Attendances",
                "unique_together": {("event", "volunteer")},
            },
        ),
    ]
