# Generated by Django 5.2.3 on 2026-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("donation", "Donation"),
                            ("volunteer", "Volunteer"),
                            ("partnership", "Partnership"),
                            ("media", "Media/Press"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "reply",
                    models.TextField(
                        blank=True, help_text="Staff reply to this message"
                    ),
                ),
                ("replied_by", models.CharField(blank=True, max_length=100)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_replied", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
