# Generated by Django 5.2.3 on 2026-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "venue",
                    models.CharField(
                        help_text="Location/venue of the event", max_length=200
                    ),
                ),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the event"
                    ),
                ),
                (
                    "is_upcoming",
                    models.BooleanField(
                        default=True, help_text="Show this event on the website"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Event image (optional)",
                        null=True,
                        upload_to="events/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date"],
            },
        ),
    ]
